### ISSUE TITLE
Missing w3c.json

### ISSUE THREAD

**Issue by plehegar** [w3c/miniapp-white-paper#1]
See https://w3c.github.io/w3c.json.html

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/mini-app-white-paper/commit/952beaba557e25bbcc15eaffaa415def1a1031aa

**Comment by foolip** [comment]
@plehegar have you filed issues like this for all repos without a w3c.json? What do you think of https://github.com/w3c/validate-repos/issues/74?

**Comment by plehegar** [comment]
@foolip I did some, following your ping on https://github.com/w3c/validate-repos/issues/74 . Part of my reasons was to figure out whether it was worth it.
